### ISSUE TITLE
Provide key to strongly sign the assembly

### ISSUE THREAD

**Issue by MovGP0** [NickStrupat/NameOf#3]
In order to avoid compiler errors in strongly signed assemblies, the NameOf.Fody project should be signed with an .pfx key: 

https://msdn.microsoft.com/en-us/magazine/cc163583.aspx

**Comment by NickStrupat** [comment]
I'm willing to "strong-name" Name.Of.dll with an .snk file, is that all that's needed for your case?

**Comment by MovGP0** [comment]
I am not sure if that works for libraries that ship with a public distributed application. :-/ 

Let's try it with the .snk file first...

**Comment by NickStrupat** [comment]
Name.Of.dll shouldn't be distributed because after a successful weaving, all references to it have been replaced with string literals. It just needs to be OK during compile, but after the compile and weaving it is removed and Name.Of.dll doesn't get put in the build output directory (at least it shouldn't)

**Comment by NickStrupat** [comment]
I'm signing Name.Of.dll in the latest version and NuGet package 0.8.2 with a .snk file. Could you check if that is allowing you to build?

**Comment by NickStrupat** [comment]
Is your issue resolved? Can I close this?

**Comment by MovGP0** [comment]
I still got the error: 

    Error	2125	Assembly '..\packages\NameOf.Fody.0.8.3\lib\Name.Of.dll' must be strong signed in order to be marked as a prerequisite.

The problem seems to have to do with the Click-Once publishing settings. 

Solution (Visual Studio): 

* Right-click the project and select "Properties"
* Go to "Publish" tab
* Select "Prerequisites"
* Search for "Name.Of.dll" and set "Publish Status" to "Exclude"
